### ISSUE TITLE
Unable to `create_numpy`, voxelization is throwing out of bounds

### ISSUE THREAD

**Issue by reaganmcf** [miccai21/2270#1]
First of all, great resource! I have been tinkering with it and have unfortunately run into a bit of a wall.

I'm doing the preprocessing steps on the same Dataset that is mentioned in the `README`, but am getting the following error from `voxelization` when calling `create_numpy` on a valid `.yml` file. We have tried the same command on multiple patient dicom/stl pairs, and can't seem to get past this.

Here is the error we are encountering:
```py
IndexError                                Traceback (most recent call last)
<ipython-input-15-57adb5df1888> in voxelization(dcm_path, stl, fill_holes)
     28         try:
---> 29             prostata[z, y, x] = (0, 1, 0, 1)
     30         except IndexError as e:

IndexError: index -67 is out of bounds for axis 0 with size 60

During handling of the above exception, another exception occurred:

IndexError                                Traceback (most recent call last)
<ipython-input-19-e02619e09167> in <module>
----> 1 npys = create_numpy("./yamls/prostate.yml")

<ipython-input-11-e6c72c1cc1a5> in create_numpy(yaml_dir)
     35             stl_path = os.path.join(label).replace("\\","/")
     36             print(stl_path)
---> 37             gt, _ = voxelization(dcm_path, stl_path)
     38             npys.append(gt)
     39             np.save(os.path.join(base_path, 'npys', os.path.basename(label)[:-4].replace("\\","/") + '.npy'), gt)

<ipython-input-15-57adb5df1888> in voxelization(dcm_path, stl, fill_holes)
     29             prostata[z, y, x] = (0, 1, 0, 1)
     30         except IndexError as e:
---> 31             prostata[min(z, bounds[0]), min(y, bounds[1]), min(x, bounds[2])] = (0, 1, 0, 1)
     32 
     33     if fill_holes:

IndexError: index -67 is out of bounds for axis 0 with size 60
```

We are only trying to get 2 patients from the dataset to work, hence our small .yml file. Here it just in case it might be the cause of the issue
```yml
images:
- location: dicoms/Prostate-MRI-US-Biopsy-0001/06-28-2009-MRI PROSTATE W WO CONTRAST-51743/11.000000-t2spcrstaxial
    oblProstate-90221
  values:
    Surface: ./stls/Prostate-MRI-US-Biopsy-0001-ProstateSurface-seriesUID-1.3.6.1.4.1.14519.5.2.1.266717969984343981963002258381778490221.STL
    Target1: ./stls/Prostate-MRI-US-Biopsy-0001-Target1-seriesUID-1.3.6.1.4.1.14519.5.2.1.266717969984343981963002258381778490221.STL
- location: dicoms/Prostate-MRI-US-Biopsy-0002/03-26-2009-MRI PROSTATE W WO CONTRAST-20097/10.000000-t2spcrstaxial
    oblProstate-22803
  values:
    Surface: ./stls/Prostate-MRI-US-Biopsy-0002-ProstateSurface-seriesUID-1.3.6.1.4.1.14519.5.2.1.186749128823666050588710146976747922803.STL
    Target1: ./stls/Prostate-MRI-US-Biopsy-0002-Target1-seriesUID-1.3.6.1.4.1.14519.5.2.1.186749128823666050588710146976747922803.STL
name: Prostate-MRI-US-Biopsy
```

If there is any other information I can provide in order to help debug this issue let me know and I will provide it. Thanks!
